### ISSUE TITLE
Pin list enhancements

### ISSUE THREAD

**Issue by naglepuff** [atlascope/atlascope#176]
The sidebar's Pin list currently only shows the pins on the current investigation and allows hiding/showing those pins. This feature would benefit from some enhancements. Some ideas include:

- [x] Responding the zoom/pan. The pin list could listen to zoom/pan events and filter the list to only show pins that are currently in the viewing window, or bubble those pins up to the top of the list. (#181)
- [ ] A button to zoom/center on one pin (#182)
- [ ] The ability to toggle pins from the sidebar, rather than clicking on the map (#183)
- [x] Show/hide all pins (#184)

**Comment by waxlamp** [comment]
Good ideas. Probably good to spin these out into individual GitHub issues.
